/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApiImageUploadUrlBean.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLPoiApiImageUploadUrlBean (0 custom class methods, 1 custom properties)

#import "GTLPoiApiImageUploadUrlBean.h"

// ----------------------------------------------------------------------------
//
//   GTLPoiApiImageUploadUrlBean
//

@implementation GTLPoiApiImageUploadUrlBean
@dynamic url;
@end
