/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API

#import "GTLPoiApiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopePoiApiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
