/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApiPoiOverviewBean.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLPoiApiPoiOverviewBean (0 custom class methods, 7 custom properties)

#import "GTLPoiApiPoiOverviewBean.h"

// ----------------------------------------------------------------------------
//
//   GTLPoiApiPoiOverviewBean
//

@implementation GTLPoiApiPoiOverviewBean
@dynamic latitude, longitude, poiId, poiName, rating, shortPoiDescription,
         thumbnailBase64;
@end
