/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApiPoiCreateBean.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLPoiApiPoiCreateBean (0 custom class methods, 5 custom properties)

#import "GTLPoiApiPoiCreateBean.h"

// ----------------------------------------------------------------------------
//
//   GTLPoiApiPoiCreateBean
//

@implementation GTLPoiApiPoiCreateBean
@dynamic imageBlobKey, latitude, longitude, poiDescription, poiName;
@end
