/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApiPoiDetailBean.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLPoiApiPoiDetailBean (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLPoiApiPoiOverviewBean;

// ----------------------------------------------------------------------------
//
//   GTLPoiApiPoiDetailBean
//

@interface GTLPoiApiPoiDetailBean : GTLObject

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (nonatomic, copy) NSString *descriptionProperty;

@property (nonatomic, retain) NSNumber *imageSize;  // longLongValue
@property (nonatomic, retain) NSNumber *imageUpdateTime;  // longLongValue
@property (nonatomic, copy) NSString *imageUrl;
@property (nonatomic, retain) GTLPoiApiPoiOverviewBean *overview;
@end
