/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApiPoiDetailBean.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLPoiApiPoiDetailBean (0 custom class methods, 5 custom properties)

#import "GTLPoiApiPoiDetailBean.h"

#import "GTLPoiApiPoiOverviewBean.h"

// ----------------------------------------------------------------------------
//
//   GTLPoiApiPoiDetailBean
//

@implementation GTLPoiApiPoiDetailBean
@dynamic descriptionProperty, imageSize, imageUpdateTime, imageUrl, overview;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"descriptionProperty" : @"description"
  };
  return map;
}

@end
