/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API

#import "GTLPoiApiConstants.h"

#import "GTLPoiApiImageUploadUrlBean.h"
#import "GTLPoiApiPoiCreateBean.h"
#import "GTLPoiApiPoiDetailBean.h"
#import "GTLPoiApiPoiOverviewBean.h"
#import "GTLPoiApiPoiOverviewListBean.h"

#import "GTLQueryPoiApi.h"
#import "GTLServicePoiApi.h"
