/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApiPoiOverviewListBean.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLPoiApiPoiOverviewListBean (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLPoiApiPoiOverviewBean;

// ----------------------------------------------------------------------------
//
//   GTLPoiApiPoiOverviewListBean
//

@interface GTLPoiApiPoiOverviewListBean : GTLObject
@property (nonatomic, retain) NSArray *list;  // of GTLPoiApiPoiOverviewBean
@end
