/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPoiApiPoiCreateBean.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLPoiApiPoiCreateBean (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLPoiApiPoiCreateBean
//

@interface GTLPoiApiPoiCreateBean : GTLObject
@property (nonatomic, copy) NSString *imageBlobKey;
@property (nonatomic, retain) NSNumber *latitude;  // doubleValue
@property (nonatomic, retain) NSNumber *longitude;  // doubleValue
@property (nonatomic, copy) NSString *poiDescription;
@property (nonatomic, copy) NSString *poiName;
@end
