/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryPoiApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryPoiApi (4 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLPoiApiPoiCreateBean;

@interface GTLQueryPoiApi : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, assign) double latitude;
@property (nonatomic, assign) double longitude;
@property (nonatomic, assign) NSInteger maxCount;
@property (nonatomic, assign) long long poiId;

#pragma mark - Service level methods
// These create a GTLQueryPoiApi object.

// Method: poiApi.getImageUploadUrl
//  Authorization scope(s):
//   kGTLAuthScopePoiApiUserinfoEmail
// Fetches a GTLPoiApiImageUploadUrlBean.
+ (instancetype)queryForGetImageUploadUrl;

// Method: poiApi.getPoiDetails
//  Authorization scope(s):
//   kGTLAuthScopePoiApiUserinfoEmail
// Fetches a GTLPoiApiPoiDetailBean.
+ (instancetype)queryForGetPoiDetailsWithPoiId:(long long)poiId;

// Method: poiApi.getPoiOverviewList
//  Authorization scope(s):
//   kGTLAuthScopePoiApiUserinfoEmail
// Fetches a GTLPoiApiPoiOverviewListBean.
+ (instancetype)queryForGetPoiOverviewListWithLatitude:(double)latitude
                                             longitude:(double)longitude
                                              maxCount:(NSInteger)maxCount;

// Method: poiApi.insertPoi
//  Authorization scope(s):
//   kGTLAuthScopePoiApiUserinfoEmail
// Fetches a GTLPoiApiPoiOverviewBean.
+ (instancetype)queryForInsertPoiWithObject:(GTLPoiApiPoiCreateBean *)object;

@end
