/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryPoiApi.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   poiApi/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryPoiApi (4 custom class methods, 5 custom properties)

#import "GTLQueryPoiApi.h"

#import "GTLPoiApiImageUploadUrlBean.h"
#import "GTLPoiApiPoiCreateBean.h"
#import "GTLPoiApiPoiDetailBean.h"
#import "GTLPoiApiPoiOverviewBean.h"
#import "GTLPoiApiPoiOverviewListBean.h"

@implementation GTLQueryPoiApi

@dynamic fields, latitude, longitude, maxCount, poiId;

#pragma mark - Service level methods
// These create a GTLQueryPoiApi object.

+ (instancetype)queryForGetImageUploadUrl {
  NSString *methodName = @"poiApi.getImageUploadUrl";
  GTLQueryPoiApi *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLPoiApiImageUploadUrlBean class];
  return query;
}

+ (instancetype)queryForGetPoiDetailsWithPoiId:(long long)poiId {
  NSString *methodName = @"poiApi.getPoiDetails";
  GTLQueryPoiApi *query = [self queryWithMethodName:methodName];
  query.poiId = poiId;
  query.expectedObjectClass = [GTLPoiApiPoiDetailBean class];
  return query;
}

+ (instancetype)queryForGetPoiOverviewListWithLatitude:(double)latitude
                                             longitude:(double)longitude
                                              maxCount:(NSInteger)maxCount {
  NSString *methodName = @"poiApi.getPoiOverviewList";
  GTLQueryPoiApi *query = [self queryWithMethodName:methodName];
  query.latitude = latitude;
  query.longitude = longitude;
  query.maxCount = maxCount;
  query.expectedObjectClass = [GTLPoiApiPoiOverviewListBean class];
  return query;
}

+ (instancetype)queryForInsertPoiWithObject:(GTLPoiApiPoiCreateBean *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"poiApi.insertPoi";
  GTLQueryPoiApi *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLPoiApiPoiOverviewBean class];
  return query;
}

@end
